apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: assisted-service-monitor
  namespace: assisted-installer
  labels:
    name: assisted-service-monitor
    app: assisted-service
spec:
  namespaceSelector:
    matchNames:
      - assisted-installer
  selector:
    matchLabels:
      app: assisted-service
  endpoints:
    - interval: 30s
      port: assisted-service
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      params:
        'match[]': 
          - '{__name__=~".+"}'
