apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-instance
  namespace: assisted-installer
  labels:
    name: grafana-instance
    app: grafana-app
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana-app
