apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus-route
  namespace: assisted-installer
  labels:
    name: prometheus-route
    app: prometheus-app
    operated-prometheus: "true"
spec:
  path: /
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None
