{
 "title": "QE Assisted Service Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "OpenShift_Version", "label": "OpenShift_Version", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Clusters Created ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})"
    }
   ]
  },
  {
   "title": "Installation Started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})"
    }
   ]
  },
  {
   "title": "Installation Passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"installed\"})"
    }
   ]
  },
  {
   "title": "Installation Canceled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"canceled\"})"
    }
   ]
  },
  {
   "title": "Installation Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"error\"})"
    }
   ]
  },
  {
   "title": "Creation vs Installation rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started{openshiftVersion=~\"$OpenShift_Version\"}))[$__range:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})[$__range:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})",
     "legendFormat": "Clusters Created "
    },
    {
     "expr": "count(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\",method=\"POST\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_creations{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",emailDomain=~\".+\"}))",
     "legendFormat": "ISO generated"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})",
     "legendFormat": "Installation Started"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"installed\"})",
     "legendFormat": "Installation Passed"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"error\"})",
     "legendFormat": "Installation Failed"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"canceled\"})",
     "legendFormat": "Installation Canceled"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\"})",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Average Phases Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"Done\"}) / sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{clusterId=~\".+\", openshiftVersion=~\"$OpenShift_Version\",result=\"Done\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Total Request Rate By Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{clusterId=~\".*\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total Request Rate By Handler",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{clusterId=~\".*\",endpoint=\"assisted-service\"}) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}